apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: totp-manager
    includeSelectors: false

resources:
  - configmap.yaml
  - postgres-cluster.yaml
  - migrate-job.yaml
  - deployment.yaml
  - ingress.yaml

images:
  - name: totp-manager
    newTag: latest
