"""Add column1 to test_items

Revision ID: 06fa8a8668cd
Revises: 641bc3f97a7d
Create Date: 2025-07-09 16:20:05.409928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06fa8a8668cd'
down_revision: Union[str, Sequence[str], None] = '641bc3f97a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('value', sa.String(length=100), nullable=False))
    op.add_column('test_items', sa.Column('column1', sa.String(length=100), nullable=False))
    op.drop_column('test_items', 'blabla')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('blabla', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('test_items', 'column1')
    op.drop_column('test_items', 'value')
    # ### end Alembic commands ###
