"""rename blabla to value in test_items

Revision ID: 359289ee28ff
Revises: 7cb922171af4
Create Date: 2025-07-09 16:11:39.774002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '359289ee28ff'
down_revision: Union[str, Sequence[str], None] = '7cb922171af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('value', sa.String(length=100), nullable=False))
    op.drop_column('test_items', 'blabla')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('blabla', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('test_items', 'value')
    # ### end Alembic commands ###
