"""Rename test_items.name to blabla

Revision ID: 7cb922171af4
Revises: e7af0ab84a46
Create Date: 2025-07-09 16:08:26.063912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7cb922171af4'
down_revision: Union[str, Sequence[str], None] = 'e7af0ab84a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('blabla', sa.String(length=100), nullable=False))
    op.drop_column('test_items', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('test_items', 'blabla')
    # ### end Alembic commands ###
