"""Update

Revision ID: cb6f23e5a487
Revises: 06fa8a8668cd
Create Date: 2025-07-09 16:21:17.256049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6f23e5a487'
down_revision: Union[str, Sequence[str], None] = '06fa8a8668cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('column2', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_items', 'column2')
    # ### end Alembic commands ###
