name: Deploy TOTP Manager

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: srv.aw3.dev
          username: 2fa
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -Eeuo pipefail

            echo "→ cd /home/2fa/totp-manager"
            cd /home/2fa/totp-manager

            echo "→ git pull"
            git pull --ff-only

            echo "→ build tailwindcss"
            cd tailwindcss
            npm install
            npm run build

            echo "→ circusctl restart 2fa"
            if ! circusctl restart 2fa; then
              echo "✖ circusctl restart failed"; exit 1
            fi

            echo "→ check circusctl status 2fa"
            status_out="$(circusctl status 2fa || true)"
            echo "$status_out"
            # consider OK if output contains active / running / action
            if ! echo "$status_out" | grep -Eiq '(active|running|action)'; then
              echo "✖ 2fa process is not in an OK state"; exit 1
            fi

            echo "→ healthcheck https://2fa.aw3.dev/health"
            health="$(curl -fsS https://2fa.aw3.dev/health || true)"
            echo "$health"
            # must contain {"status":"ok"}
            if ! echo "$health" | grep -q '"status":"ok"'; then
              echo "✖ Healthcheck failed"; exit 1
            fi

            echo "✅ Deploy OK"
